### ISSUE TITLE
Lauching unit tests?

### ISSUE THREAD

**Issue by jpetitcolas** [geocoder-php/GeocodableBehavior#15]
I am currently fixing the lack of `IsGeocodingNecessary` method when no geocoder is set. The fix is implemented, yet I can't suceed in launching unit tests.

I downloaded Composer and then installed dependencies. Then, I launched the tests:

```
curl -s http://getcomposer.org/installer | php
php composer.phar install
phpunit tests
```

Yet, I got following issue:

```
PHPUnit 3.7.1 by Sebastian Bergmann.

Configuration read from /home/jpetitcolas/dev/www/GeocodableBehavior/phpunit.xml.dist

.........PHP Fatal error:  Class 'Geocoder\Geocoder' not found in /home/jpetitcolas/dev/www/GeocodableBehavior/vendor/propel/propel1/generator/lib/util/PropelQuickBuilder.php(151) : eval()'d code on line 4346
```

Am I missing a point?

**Comment by willdurand** [comment]
--dev?

## 

William Durand | http://www.williamdurand.fr

**Comment by jpetitcolas** [comment]
What do you mean? I do not see any options like `--dev` in the documentation of PHPUnit. :)

**Comment by willdurand** [comment]
Dude, check the .travis.yml file.

## 

William Durand | http://www.williamdurand.fr

**Comment by jpetitcolas** [comment]
Indeed, I did not know about this file. Thanks. :)
