### ISSUE TITLE
locate GeocodableBehaviorQueryBuilderModifier in build.properties

### ISSUE THREAD

**Issue by smhg** [geocoder-php/GeocodableBehavior#19]
I can load the main GeocodableBehavior class (installed with composer) just fine with:

`propel.behavior.geocodable.class = ${propel.project.dir}.vendor.willdurand.propel-geocodable-behavior.src.GeocodableBehavior`

but this throws an error during building because `GeocodableBehaviorQueryBuilderModifier` can't be found.

What is the "recommended" way to tell `propel-gen` about its location?

**Comment by smhg** [comment]
I had my "paths" wrong (on Windows).
As soon as I used the `propel-gen` wrapper in `vendor/bin` (Composer), things went beautifully smooth.

**Comment by willdurand** [comment]
\o/
