### ISSUE TITLE
Bug in "filterByDistanceFrom"

### ISSUE THREAD

**Issue by pascalgardeur** [geocoder-php/GeocodableBehavior#20]
Hello,

I'm using Propel with Postgresql on a Symfony2 project.
I have a list of geolocated items, and the "filterByDistanceFrom" method fails in the case where parameters are identical to the values ​​of the database, due to rounding difference between PHP "cos(deg2rad(x))" and Postgresql "COS(RADIANS(x))".

Exemple of one item in my database :
- latitude : 49.081776
- longitude : 3.743992

This call "filterByDistanceFrom( 49.081776, 3.743992 )" fails with the message "out of range".

The final calculation is "ACOS(1.00000000000000092485197921763)" instead of "ACOS(1.0)"

Thank you

**Comment by willdurand** [comment]
Any hint on how to fix this?

**Comment by pascalgardeur** [comment]
Postgres : COS(RADIANS(49.081776)) = 0.654981194002048
PHP : cos(deg2rad(49.081776) = 0.65498119400205

One solution could be truncate precision, something like this :
Postgres : round( cast( COS(RADIANS(49.081776)) as numeric ), 14 ) = 0.65498119400205
PHP : round ( cos(deg2rad(49.081776)), 14 ) = 0.65498119400205

Another solution could be test the range of value before ACOS.
$sql = 'ABS(%s \* ACOS(' .
             ' CASE WHEN CAST ( %s \* COS(RADIANS(%s)) \* COS(RADIANS(%s) - %s) + %s \* SIN(RADIANS(%s)) AS NUMERIC ) <@ NUMRANGE(-1,1)' .
             '      THEN %s \* COS(RADIANS(%s)) \* COS(RADIANS(%s) - %s) + %s \* SIN(RADIANS(%s))' .
             '      ELSE round( CAST ( %s \* COS(RADIANS(%s)) \* COS(RADIANS(%s) - %s) + %s \* SIN(RADIANS(%s)) AS NUMERIC ), 0 )' .
             ' END' .
         '))';

**Comment by pascalgardeur** [comment]
Or simply rounding the final value:

round( 1.00000000000000092485197921763 , 14 ) = 1.00000000000000

$sql = 'ABS(%s \* ACOS( ROUND( CAST ( %s \* COS(RADIANS(%s)) \* COS(RADIANS(%s) - %s) + %s \* SIN(RADIANS(%s)) AS NUMERIC ), 14 ) ))';

**Comment by willdurand** [comment]
should be fixed by PR #31
