### ISSUE TITLE
Separate distance column method in query class

### ISSUE THREAD

**Issue by smhg** [geocoder-php/GeocodableBehavior#27]
I think it would be great to have the [Distance](https://github.com/geocoder-php/GeocodableBehavior/blob/master/src/templates/queryFilterByDistanceFrom.php#L23-32) column as a separate query method (something like `withDistance`).

That would facilitate making custom queries like

``` php
XxxQuery::create()
  ->withDistance($latitude, $longitude)
  ->limit(10)
  ->orderByDistance()
  ->find();
```

to find the 10 closest matches to a specific location.

What do you think?

One difficulty: is there a way around the re-use of the prepared statement in the [where clause](https://github.com/geocoder-php/GeocodableBehavior/blob/master/src/templates/queryFilterByDistanceFrom.php#L36) in `filterByDistanceFrom`?

A less disruptive option is to make the `$distance` parameter to `filterByDistanceFrom` optional (and not add the where clause when `null`).
I personally like the modularity of `withDistance` though.

I'm happy to send a PR after your feedback.

**Comment by willdurand** [comment]
Yep, :+1:
