### ISSUE TITLE
filterByDistanceFrom return NULL for distance 0

### ISSUE THREAD

**Issue by janwalther** [geocoder-php/GeocodableBehavior#30]
When a row in the database has the exact same latitude and longitude as I am querying filterByDistanceFrom than the dataset is not found because the distance is NULL.

My dataset (datatype in MySQL: FLOAT):
lat = 51
lon = 9

SELECT ABS(6371 \* ACOS(0.62932039104984 \* COS(RADIANS(LocationAttributeValue.lat)) \* COS(RADIANS(LocationAttributeValue.lon) - 0.15707963267949) + 0.77714596145697 \* SIN(RADIANS(LocationAttributeValue.lat)))) Distance 
FROM Table

returns NULL for this row (other rows with different latitudes / longitudes have right distances).

**Comment by willdurand** [comment]
should be fixed by PR #31
