### ISSUE TITLE
Does this behavior works with propel 2

### ISSUE THREAD

**Issue by kentpachi** [geocoder-php/GeocodableBehavior#33]
Hello,

The documentation says 1.6 or above for the version of propel.

But will it works with propel starting from 2 ?

thanks

**Comment by kentpachi** [comment]
Hello again,

after few tests i'm getting some problem with propel 2

First the GeocodableBehavior.php does not contains correct psr namespace

```
namespace Propel\Generator\Behavior\Geocodable;
use Propel\Generator\Model\Behavior;
```

so when i issue propel diff it says "unknown class Behavior", so i added thoses lines at the top of the file ( also tried to add behavior path in build.properties ...)

next while issuing propel diff, i'm getting

```
 Call to undefined method Propel\Generator\Model\Table::containsColumn() in /var/www/[..]/src/Propel/Generator/Behavior/Geocodable/GeocodableBehavior.php on line 53
```

I think the class is too old maybe ? should i continue debugging it or just give up ? what do you advise ? I might be doing something wrong...

thanks in advance.

**Comment by willdurand** [comment]
Nope, it does not work. It should be quite easy to make compatible, but I won't do that myself at the moment.

**Comment by kentpachi** [comment]
Thank you for your reply.

I'm trying to achieve this, i'm just lookin for propel 2 equivalent to getStubPeerBuilder ( to get $peerName )

any tips on this ?

**Comment by willdurand** [comment]
There is no more PEER classes. It is probably in the Query class, or in the TableMap IIRC.
