### ISSUE TITLE
Deprecate this package

### ISSUE THREAD

**Issue by atymic** [geocoder-php/GeocodableBehavior#37]
This seems to be abandoned. Should we archive the github repo?

cc @Nyholm

**Comment by Nyholm** [comment]
Yeah. I think so.. I've honestly never seen this package =)

**Comment by willdurand** [comment]
It's fine to archive it indeed :)

**Comment by atymic** [comment]
(I don't actually have permissions to archive so if one of you could :)) 
Thanks

**Comment by Nyholm** [comment]
I'll do it. 

Thank you
