### ISSUE TITLE
setting api_key in configuration rather than schema

### ISSUE THREAD

**Issue by mrbase** [geocoder-php/GeocodableBehavior#8]
it would be great to be able to set the api_key in propels configuration rather than in the schema file

ideally moving from dev servers to prod servers should not resolve in rebuilding your model

**Comment by willdurand** [comment]
Agreed, would you mind working on a patch ? I don't have any time for now

**Comment by mrbase** [comment]
will give it a try

**Comment by mrbase** [comment]
i have an implementation [here](https://github.com/mrbase/GeocodableBehavior/commit/1ac584c1712a48753cc4fec941c0698037eebc48) which i'm not 100% satisfied with, but i found no other way to load the key via ex. symfony

the patch also includes an extended "is modified" check

**Comment by mrbase** [comment]
hi @willdurand, is this usefull, or should i try to find another solution ?

**Comment by willdurand** [comment]
Seems fine, would you mind make a PR ? With some unit tests please.

2012/2/10 ulrik nielsen <
reply@reply.github.com

**Comment by mrbase** [comment]
should not be a problem, in which env have you done unit testing ?
running the tests under sf2 standard ed. fails due to path mismatch and missing files

i installed the behavior using the deps file:

```
....
[GeocodableBehavior]
    git=git@github.com:mrbase/GeocodableBehavior.git
    target=/propel-behaviors/GeocodableBehavior

[Geocoder]
    git=http://github.com/willdurand/Geocoder.git
```

**Comment by willdurand** [comment]
Thank you for your PR.
